### ISSUE TITLE
Missing dependency in package.json

### ISSUE THREAD

**Issue by wouterSeyen** [auth0-samples/auth0-angular-samples#313] opened 2022-10-27 13:45 UTC
When downloading the code and running `npm install && npm start` the compilation fails with errors stating `@popperjs/core` is missing.

```
Error: node_modules/@ng-bootstrap/ng-bootstrap/util/positioning.d.ts:1:55
 - error TS2307: Cannot find module '@popperjs/core' or its corresponding type declarations.
```

**Comment by frederikprijck** [comment] 2022-10-27 13:52
Thanks for reporting this.

I did a fresh clone, rm -rf node_modules, ran npm i and npm start and have no issues.

It has installed popper because of ng-bootstrap, as expected:

![image](https://user-images.githubusercontent.com/2146903/198303349-c46da0e7-276c-4a0a-8aaf-05ef8116e962.png)

Anything you are doing different that could result in this?

**Comment by wouterSeyen** [comment] 2022-10-27 14:08
Hi @frederikprijck,
I downloaded the sample from within Auth0 in the Quickstart of a SPA
![image](https://user-images.githubusercontent.com/7555213/198307550-94dd4ee4-72bd-4ae2-9131-17ddbe2265bc.png)
So I'm not using the code in this repository directly, but definitely something derived from it as you choose to download it, or "view on github" which leads you here.

**Comment by frederikprijck** [comment] 2022-10-27 14:11
The Download Sample button should download the Sample-01 folder, which is the one I tried.

![image](https://user-images.githubusercontent.com/2146903/198308721-20801393-119a-4bb7-9d2b-cdc1c2f15344.png)

**Comment by wouterSeyen** [comment] 2022-10-27 14:33
I've tried it with both
- node: v18.12.0 with npm v8.19.2
- node: v16.17.0 with npm v8.15.0
with the same result.
For reference, I'm working on a Windows 11 machine.
I also have the same result if I clone the repository and run the commands there.

**Comment by frederikprijck** [comment] 2022-10-27 14:40
Thanks, will see if I can reproduce this in Windows. Tried a couple of different ways on OSX, but been unable to reproduce it on that.

**Comment by wouterSeyen** [comment] 2022-10-28 06:58
Hi @frederikprijck,
I also asked a colleague to do same actions, he installed the packages and launched the application without issues, so seems to be an issue with my own installation

**Comment by frederikprijck** [comment] 2022-10-28 07:29
I am going to close this for now, let me know if you believe there is anything we need to change here!

**Closed by frederikprijck** 2022-10-28 07:29 UTC
