### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by guilhermecgs** [auth0-samples/auth0-angular-samples#126] opened 2018-11-12 11:36 UTC
```
mydir>npm start

> 06-single-sign-on@1.0.0 start mydir
> npm-run-all --parallel run:app-one run:app-two


> 06-single-sign-on@1.0.0 run:app-one mydir
> cd sso-app-one && ng serve --host 0.0.0.0 --port='3000'


> 06-single-sign-on@1.0.0 run:app-two mydir
> cd sso-app-two && ng serve --host 0.0.0.0 --port='3001'

Your global Angular CLI version (6.1.2) is greater than your local
version (1.7.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Your global Angular CLI version (6.1.2) is greater than your local
version (1.7.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
** NG Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **
** NG Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **
  0% compiling 10% building modules 3/3 mo 10% building modules 3/4 modules 1 active ...rver\client\index.js?http://0.0.0.0:0events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:4200
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at doListen (net.js:1505:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 06-single-sign-on@1.0.0 run:app-two: `cd sso-app-two && ng serve --host 0.0.0.0 --port='3001'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 06-single-sign-on@1.0.0 run:app-two script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by jimmyjames** [comment] 2019-06-24 18:34
It looks like you already have something running on port 4200 (`Error: listen EADDRINUSE 0.0.0.0:4200`). Also possible this sample has changed since reporting, but as I'm not able to reproduce, going to close it.

**Closed by jimmyjames** 2019-06-24 18:34 UTC
