### ISSUE TITLE
Auth0 angular client keeps redirect to localhost and not host domain

### ISSUE THREAD

**Issue by liorko87** [auth0-samples/auth0-angular-samples#196] opened 2020-07-27 12:25 UTC
I managed to implement Auth0 Angular quickstart to localhost.
When I’m trying to change the local host to a name domain It keeps to redirect to the localhost address.

I added the name domain to allowed callback URLs at the app settings but it didn’t works.

Any suggestions?

Lior

**Comment by stevehobbsdev** [comment] 2020-08-13 12:47
Apologies for the radio silence here @liorko87  - can you show me how the SDK is being initialized?

Normally you would specify the `redirect_uri` property when setting up, which will cause Auth0 to redirect you to the right place.

**Comment by liorko87** [comment] 2020-08-17 19:30
@stevehobbsdev Thank you for the reply.
Please the source code [here](https://github.com/cryptobiu/MATRIX/blob/dev/WebApp/frontend/src/app/Services/auth.service.ts)

**Comment by stevehobbsdev** [comment] 2020-10-20 10:45
@liorko87 So far I've been unable to reproduce this, unfortunately.

We have since upgraded the samples to use our new [Angular SDK](https://github.com/auth0/auth0-angular), which should provide a much better experience when using Angular with Auth0, and I would encourage you to give it a try.

Closing this for now, but feel free to raise any additional questions you may have.

**Closed by stevehobbsdev** 2020-10-20 10:45 UTC
