### ISSUE TITLE
Race condition when calling handleAuthCallback in the sample code

### ISSUE THREAD

**Issue by d-led** [auth0-samples/auth0-angular-samples#188] opened 2020-04-01 17:59 UTC
## Problem

the [Angular: Login sample code](https://auth0.com/docs/quickstart/spa/angular2/01-login) causes a race condition: an unbounded redirect loop, sometimes succeeding to authenticate the app, sometimes not.

## Solution

just use the [solution](https://community.auth0.com/t/angular-8-isauthenticated-race-condition/37474) by @camdenbrown (@ceb-luclin ?), which does not exhibit the problem

**Comment by stevehobbsdev** [comment] 2020-04-07 14:59
Thanks for raising this @d-led, let me take a look at this properly over the next few days and see if I can get it solved.

**Comment by XavierTalpe** [comment] 2020-04-15 08:58
@stevehobbsdev any update on this?

**Comment by stevehobbsdev** [comment] 2020-05-28 17:01
@XavierTalpe Not yet, apologies for the radio silence here. Let me get a look shortly. In the meantime we would of course review any PR that was raised to help fix this.

**Comment by Ro3A** [comment] 2020-06-08 01:30
@stevehobbsdev 

Any update on this? I'm running into this as well on a side project at home, but we're about to start implementing this at work as well. I'm having doubts at this point especially since this issue has been open for some time. 

We're paying for this service so we don't have to work through headaches like this..

**Comment by stevehobbsdev** [comment] 2020-06-08 14:29
@Ro3A Does the [solution proposed here](https://community.auth0.com/t/angular-8-isauthenticated-race-condition/37474/3) get you unblocked in the meantime?

**Comment by Ro3A** [comment] 2020-06-08 14:46
@stevehobbsdev Unfortunately not. I spent all day yesterday implementing the various solutions but that is not a variant I tried. 

I'm also concerned about the same site warnings. I know there are github issues on that as well. 

I'm sure you guys are like most dev shops - overburdened and swamped. Seeing how long these issues have been open, and the fact that even the sample project has this issue has me concerned...

Would it be a better idea to implement our own UI's and use our backend to fetch tokens on behalf of the user? Is that a more stable flow?

**Comment by camden-brown** [comment] 2020-06-08 14:59
Sorry for the many Github accounts.... lost access to my original =(

@Ro3A can you perhaps show an example of the issue you're running into? I can try and take a look to help diagnose. The biggest thing for me is just keeping in mind the idea of asynchronous design patterns and how things will be completed and in what order. Also how Angular guards/resolvers operate.

Is there a specific scenario you are having difficulty with?

**Comment by Ro3A** [comment] 2020-06-08 15:38
@camden-brown After checking out the variant you posted, I think it will work. 

This is a greenfield app - so the issues I'm running into are precisely the same ones for this issue and the other one on AuthGuard. As well as the isAuthenticated observable wasn't firing when using an async pipe on my nav bar. 

We use Angular 9 / RxJS heavily at work on very non-trivial applications so I'm pretty well versed in it, but, we are generating our own tokens with a .net core back-end so the auth flow is quite different. 

The real issue is the recommendation for spa users to use this library which is broken out of the box  for event he most simple of use cases, and the length of time to implement fixes, which makes me question the dev / QC process. 

I'm going to give this solution a try this evening and hopefully it resolves the issue.

**Comment by stevehobbsdev** [comment] 2020-06-08 21:34
> I'm also concerned about the same site warnings. I know there are github issues on that as well.

The SameSite warnings fall into two camps - warnings you're getting about the compatibility cookie, and warnings you're getting from some local cookies we set from the SDK.

The former is nothing to do with the SDK and everything to do with backwards-compatible cookies set by Auth0 Server, which will not affect your app. You can verify this by making sure all the SameSite flags are turned on in Chrome and check that you can still sign in properly. I'll reference [this issue](https://github.com/auth0/auth0-spa-js/issues/330#issuecomment-575252646) which has more links in it for further reading.

The latter is being dealt with by [this PR](https://github.com/auth0/auth0-spa-js/pull/472) that is currently going through review and will be pulled in very shortly.

> The real issue is the recommendation for spa users to use this library which is broken out of the box for event he most simple of use cases

It's not the library that is causing trouble here, it's the way RxJS is being utilised in this sample app that uses the library. The library itself works out of the box for the majority of people.

I will also try to validate the proposed solution this week and bring it into the sample; please let me know if it works for your particular case.

**Comment by stevehobbsdev** [comment] 2020-06-08 21:58
In order to help get this resolved, if someone could put forward clear steps that reproduce the issue. I'm unclear as to whether you're hitting this on login or working with a guard (could be both?)

I ask because I'm unable to reproduce it. I'm not saying the issue doesn't exist, just saying I'm working a bit in the dark to see if the changes I'm making are making a difference.

@camden-brown The thing that's throwing me off is that in this issue you talk about the various places you try to call `handleRedirectCallback` from, but the sample is set up in such a way that you shouldn't have to call this yourself, as it will do it automatically on page load. Or at least that's the intention.

**Comment by camden-brown** [comment] 2020-06-08 22:13
@stevehobbsdev it's honestly been quite some time since I've messed with it. I've had to refactor a few things since then. I'll try to get you some details on how I set it up tomorrow and maybe we can figure out where the disconnect is.

**Comment by turkingj** [comment] 2020-06-08 22:14
https://github.com/auth0-samples/auth0-angular-samples/issues/181#issuecomment-577144740

**Comment by stevehobbsdev** [comment] 2020-06-08 22:15
Thanks @camden-brown. In that time, the underlying SDK has been simplified in that you no longer need to use the `createAuth0Client` function that returns a promise, and can instead use the constructor directly. I think that should simplify this code a lot.

**Comment by Ro3A** [comment] 2020-06-09 00:42
@stevehobbsdev Thanks for the info on SameSite. 

I'll grabbed the sample code, and only change I made was to plug in my values on the service class (copy pasted from the quick start).

1. Clear all cookies and storage to start fresh
2. Run site with port numbers configured in Auth0
3. Logged In Successfully
4. F5 Refresh page. This may be the part you're missing.
5. Arrive back on home page, but there is no Profile section on the right side of top bar

![image](https://user-images.githubusercontent.com/19931334/84090203-0b339900-a9bf-11ea-8243-d134f9591975.png)

**Comment by Ro3A** [comment] 2020-06-09 00:45
@turkingj I implemented your solution as well, and it didn't work on F5 refresh. It worked better as I was able to make better use of isAuthenticated$ via async pipe on nav bar, but after a refresh it was a no go. But maybe I missed something.

**Comment by stevehobbsdev** [comment] 2020-06-09 10:02
@Ro3A Is this intermittent or does it happen every time on refresh?

I don't have that issue; if it happens every time, it may be down to the configuration of your Auth0 client. Things to check:

* Have you specified the application URL in the [Allowed Web Origins box](https://auth0.com/docs/quickstart/spa/angular2#configure-allowed-web-origins) when setting up your Auth0 client?
* Do you get any errors in your [Auth0 logs](https://manage.auth0.com/#/logs) relating to "failed silent auth"?
* Do you get an error page in your browser network trace from the `/authorize` endpoint? (you'll need to check the HTML response)
* If you wait 60 seconds after refreshing, do you get an error in the console?
* If you upgrade the sample app to use `@auth0/auth0-spa-js@1.9.0` does the situation improve?

Please let me know if any of the above bears any fruit.

**Comment by Ro3A** [comment] 2020-06-10 00:52
@stevehobbsdev 

Thanks for the list of questions to work through. Ultimately, I found a trailing slash was present in allowed origins. Removing the trailing slash got the sample app working. 

Some questions remain:

1) When trailing slash is present, why does login work but silent auth does not? I would have discovered the trailing slash issue much sooner if it failed outright due to incorrect configuration. In fact, I had other origins in there without a slash for my real app.

2) When silent auth fails, I would expect the app to either fully resolve itself and properly fetch the userProfile, or fail completely and prompt for login. This is what caused the confusion with the sample app.

In a non-sample app, I'd prefer to use isAuthenticated$ in the nav template since my components all use OnPush change detection. If I implement that in the sample, it works.. sort of. The page loads immediately but appears logged out initially. Then the observables update and the nav reflects the user logged in. This means the AuthGuard isn't working as it should and I'm not sure why at the moment. I can't spend more time digging in. 

So for now, I'm going to stick with Camden's solution as it better aligns the auth service with best practices and the AuthGuard works as it should.

Keep me posted on the questions above though, I'm interested in why it partially succeeded.

**Comment by stevehobbsdev** [comment] 2020-06-10 11:06
Glad you've gotten to the bottom of it. To answer your questions:

1. It's less about the trailing slash and more about the fact that the URLs have to match exactly. For silent login, only the _origin_ is checked (e.g. `https://localhost:3000`) and this value should be entered into **Allowed Web Origins** exactly (you can of course add more, comma separated). For login, the full callback URL is needed, so origin + path (if there is one). e.g. `http://localhost:3000/callback`. Again, this value should match exactly with something but in the **Allowed Callback URLs** box. The difference is that for a full interactive login, the redirect URL can be specified by you, the developer. It can be anything (with trailing slash or without) but the point is that the two values must match.

Silent logins use an iframe by default, which are cross-origin requests. For these, the app doesn't send a redirect URL; instead Auth0 server will read of the origin value from the request.

2. Silent auth can fail for a number of reasons. When it's a configuration issue the server doesn't post back a message to tell us it has failed in this way, which is why the 60 second (configurable) timeout exists. If it's a protocol failure, we get a proper error response back. I agree though that the sample could do better in this regard with showing you what to do and we'll take it on board as feedback for when we iterate on these samples in the future.

**Comment by stevehobbsdev** [comment] 2020-06-10 11:07
@d-led I'm not sure if anything in this thread has helped you resolve your issue as it's been hi-jacked a bit. Can you let me know if you're still having problems?

**Comment by camden-brown** [comment] 2020-06-12 15:30
So, looking back at what I wrote and what I have now. I only use `handleRedirectCallback` once in my `handleAuthCallback` call. `handleAuthCallback` is called in my `callback.resolver.ts` file. I believe the callback resolver is the recommended approach in the docs. There is a `callback` route with that resolver on it to figure out where to send the user to.


I think the issue is with the docs recommended approach around `handleAuthCallback`. So when the user gets redirected to the AuthGuard in the recommended approach, I'm not really sure why the assumption there is that `isAuthenticated$` is going to have the correct result. It's going to just resolve with whatever value comes back first. When the user logs in, I need to know that the login process is complete, redirect the user to the home page, and that isAuthenticated$ is going to return the correct value.

Here is my `handleAuthCallback` which returns an Observable which gets subbed to in my callback resolver.

`  handleAuthCallback(): Observable<{ loggedIn: boolean; targetUrl: string }> {
    return of(window.location.search).pipe(
      concatMap(params =>
        iif(
          () => params.includes('code=') && params.includes('state='),
          this.handleRedirectCallback$.pipe(
            concatMap(cbRes =>
              this.isAuthenticated$.pipe(
                map(loggedIn => ({
                  loggedIn,
                  targetUrl: cbRes.appState && cbRes.appState.target ? cbRes.appState.target : '/'
                }))
              )
            )
          ),
          this.isAuthenticated$.pipe(map(loggedIn => ({ loggedIn, targetUrl: null })))
        )
      )
    );
  }`

`@Injectable({ providedIn: 'root' })
export class CallbackResolver implements Resolve<void> {
  constructor(private authService: AuthService, private router: Router) {}

  resolve(): Observable<void> {
    return this.authService.handleAuthCallback().pipe(
      concatMap(result =>
        iif(
          () => result.loggedIn,
          of(null).pipe(tap(_ => this.router.navigate(['/home/dashboard']))),
          this.authService.login()
        )
      ),
      take(1)
    );
  }
}
`

`
@Injectable()
export class AuthGuard implements CanActivate {
  constructor(private authService: AuthService, private store: Store<fromStore.HomeState>) {}

  canActivate(): Observable<boolean> {
    return this.authService.isAuthenticated$.pipe(
      concatMap(result => (result ? of(true) : this.authService.login().pipe(map(_ => false))))
    );
  }
}
`

I'm sure there is probably cleaner ways to write this code but after unit testing most of it and several hundred successful user registrations I haven't had any issues. 

Hope that helps @stevehobbsdev

**Comment by PapaNappa** [comment] 2020-06-15 07:31
I also ran into the issue described here.

I also started off with the original solution from camdenbrown in the forum post.
I particularly did not like that the AuthGuard called handleAuthCallback.
The last post from camden-brown has also a bit of complexities, I think.

Here's my shot:

In the Auth0Service, I have an `initializedSubject` and `initialized$` observable from that subject.

```typescript
  // set to true once handleAuthCallback has completed
  private initializedSubject = new BehaviorSubject<boolean>(false);

  // emits once handleCallback has completed
  private initialized$ = this.initializedSubject
    .pipe(
      filter(initialized => initialized), // only when initialized is true
      take(1), // only emit a single event
    );
```

the `isAuthenticated$` can then by based on `initialized$`, because we only know for certain if the user has authenticated or not after we have been initialized:

```typescript
  isAuthenticated$ = this.initialized$
    .pipe(
      concatMapTo(this.auth0Client$),
      concatMap((client: Auth0Client) => from(client.isAuthenticated())),
    );
```

I guess `handleRedirectCallback$` stays the same:

```typescript
  handleRedirectCallback$ = this.auth0Client$.pipe(
    concatMap((client: Auth0Client) => from(client.handleRedirectCallback())),
  );
```

`localAuthSetup` also must wait on initialized:

```typescript
  localAuthSetup() {
    // This should only be called on app initialization
    // Set up local authentication streams
    const checkAuth$ = this.isAuthenticated$.pipe(
      concatMap(loggedIn => loggedIn ? this.verifyAuth() : of(false)),
      concatMap(loggedIn => {
        if (loggedIn) {
          // If authenticated, get user and set in app
          // NOTE: you could pass options here if needed
          return this.getUser$();
        }
        // If not authenticated, return stream that emits 'false'
        return of(loggedIn);
      }),
    );
    checkAuth$.subscribe((response: {[key: string]: any} | boolean) => {
      // If authenticated, response will be user object
      // If not authenticated, response will be 'false'
      this.appState.user = response as any;
    });
  }
```

`handAuthCallback` is then responsible for setting `initializedSubject` to true.
This is immediately the case when the app has not returned from authentication (no code/state params); or when `handleRedirectCallback$` finished.
I also simplified `handleAuthCallback` in that it does not need to return anything:

```typescript
  handleAuthCallback(): Observable<{loggedIn: boolean; targetUrl: string}> {
    const params = window.location.search;
    if (!(params.includes('code=') && params.includes('state='))) {
      // user has not been redirected from login, nothing to do
      this.initializedSubject.next(true);
      return;
    }

    // if the user has been redirected, handle the redirect
    this.handleRedirectCallback$
      .pipe(
        tap(() => this.initializedSubject.next(true)),
        concatMap(cbRes =>
          this.isAuthenticated$
            .pipe(
              mergeMap(loggedIn => loggedIn ? this.verifyAuth() : of(false)),
              map(loggedIn => ({
                loggedIn,
                targetUrl: cbRes.appState && cbRes.appState.target ? cbRes.appState.target : '/',
              })),
            ),
        ),
      )
      .subscribe(result => this.router.navigateByUrl(result.targetUrl));
  }
```

The AuthGuard can then simply subscribe to isAuthenticated$:

```typescript
  canActivate(
    next: ActivatedRouteSnapshot,
    state: RouterStateSnapshot,
  ): Observable<boolean> | Promise<boolean | UrlTree> | boolean {
    return this.auth.isAuthenticated$.pipe(
      mergeMap(loggedIn => {
        if (!loggedIn) {
          return this.auth.login(state.url).pipe(mapTo(false));
        }
        return of(true);
      }),
    );
  }
```

This works very well for me.

**Comment by stevehobbsdev** [comment] 2020-06-26 17:26
Thanks everyone. Let me look at how we can change the code here to make it more reliable. I'm not an Angular dev but I have some ideas, would appreciate you pitching in on the review when I raise the PR 👍

**Comment by d-led** [comment] 2020-06-26 20:06
@stevehobbsdev thanks! For now, I've kept it working with the firefox workaround, and the other proposed work-arounds. If sample code gets updated, I'd try the new version on a fresh project

**Comment by aangelos28** [comment] 2020-07-20 23:33
I am having the same issue with Angular 10 using the new Auth0 universal login experience and the Auth0 Angular sample code. In my case, I have set up a redirect in the router to map the root path ("/") and all unknown routes to the dashboard, which has an `AuthGuard`. Once I set up this redirect, I get an infinite redirection loop after authenticating. If I do not set up the redirect and attempt to navigate directly to the dashboard, there is no authentication loop.

These are the routes with the redirect set up:
```javascript
const routes: Routes = [
    { path: 'dashboard', component: DashboardComponent, canActivate: [AuthGuard] },
    { path: 'account', component: AccountComponent, canActivate: [AuthGuard] },
    { path: '**', redirectTo: 'dashboard' }
];
```

There is a simple workaround that works for now, but it definitely is a hack. In the authentication service from the sample, if I change the following code block:
```javascript
isAuthenticated$ = this.auth0Client$.pipe(
        concatMap((client: Auth0Client) => from(client.isAuthenticated())),
        tap(res => this.loggedIn = res)
    );
```
to

```javascript
isAuthenticated$ = this.auth0Client$.pipe(
        delay(500), // fixes authentication loop, but delay is a hack
        concatMap((client: Auth0Client) => from(client.isAuthenticated())),
        tap(res => this.loggedIn = res)
    );
```
the redirect loop is resolved.

**Comment by Ethras** [comment] 2020-08-12 09:31
> I also ran into the issue described here.
> 
> I also started off with the original solution from camdenbrown in the forum post.
> I particularly did not like that the AuthGuard called handleAuthCallback.
> The last post from camden-brown has also a bit of complexities, I think.
> 
> Here's my shot:
> 
> In the Auth0Service, I have an `initializedSubject` and `initialized$` observable from that subject.
> 
> ```ts
>   // set to true once handleAuthCallback has completed
>   private initializedSubject = new BehaviorSubject<boolean>(false);
> 
>   // emits once handleCallback has completed
>   private initialized$ = this.initializedSubject
>     .pipe(
>       filter(initialized => initialized), // only when initialized is true
>       take(1), // only emit a single event
>     );
> ```
> 
> the `isAuthenticated$` can then by based on `initialized$`, because we only know for certain if the user has authenticated or not after we have been initialized:
> 
> ```ts
>   isAuthenticated$ = this.initialized$
>     .pipe(
>       concatMapTo(this.auth0Client$),
>       concatMap((client: Auth0Client) => from(client.isAuthenticated())),
>     );
> ```
> 
> I guess `handleRedirectCallback$` stays the same:
> 
> ```ts
>   handleRedirectCallback$ = this.auth0Client$.pipe(
>     concatMap((client: Auth0Client) => from(client.handleRedirectCallback())),
>   );
> ```
> 
> `localAuthSetup` also must wait on initialized, or in particular when `isAuthenticated$` first resolves:
> 
> ```ts
>   localAuthSetup() {
>     // This should only be called on app initialization
>     // Set up local authentication streams
>     const checkAuth$ = this.isAuthenticated$.pipe(
>       concatMap(loggedIn => {
>         if (loggedIn) {
>           // If authenticated, get user and set in app
>           // NOTE: you could pass options here if needed
>           return this.getUser$();
>         }
>         // If not authenticated, return stream that emits 'false'
>         return of(loggedIn);
>       }),
>     );
>     checkAuth$.subscribe((response: {[key: string]: any} | boolean) => {
>       // If authenticated, response will be user object
>       // If not authenticated, response will be 'false'
>       this.appState.user = response as any;
>     });
>   }
> ```
> 
> `handAuthCallback` is then responsible for setting `initializedSubject` to true.
> This is immediately the case when the app has not returned from authentication (no code/state params); or when `handleRedirectCallback$` finished.
> I also simplified `handleAuthCallback` in that it does not need to return anything:
> 
> ```ts
>   handleAuthCallback(): Observable<{loggedIn: boolean; targetUrl: string}> {
>     const params = window.location.search;
>     if (!(params.includes('code=') && params.includes('state='))) {
>       // user has not been redirected from login, nothing to do
>       this.initializedSubject.next(true);
>       return;
>     }
> 
>     // if the user has been redirected, handle the redirect
>     this.handleRedirectCallback$
>       .pipe(
>         tap(() => this.initializedSubject.next(true)),
>         concatMap(cbRes =>
>           this.isAuthenticated$
>             .pipe(
>               map(loggedIn => ({
>                 loggedIn,
>                 targetUrl: cbRes.appState && cbRes.appState.target ? cbRes.appState.target : '/',
>               })),
>             ),
>         ),
>       )
>       .subscribe(result => this.router.navigateByUrl(result.targetUrl));
>   }
> ```
> 
> The AuthGuard can then simply subscribe to isAuthenticated$:
> 
> ```ts
>   canActivate(
>     next: ActivatedRouteSnapshot,
>     state: RouterStateSnapshot,
>   ): Observable<boolean> | Promise<boolean | UrlTree> | boolean {
>     return this.auth.isAuthenticated$.pipe(
>       mergeMap(loggedIn => {
>         if (!loggedIn) {
>           return this.auth.login(state.url).pipe(mapTo(false));
>         }
>         return of(true);
>       }),
>     );
>   }
> ```
> 
> This works very well for me.

This solution works perfectly for me. Thank you sir!

**Comment by stevehobbsdev** [comment] 2020-08-17 15:00
Thanks everyone for their comments.

I would like to highlight something that we have been working on which will totally replace these samples, which is a brand new [Auth0 SDK for Angular](https://github.com/auth0/auth0-angular). Instead of continuing to iterate on what is essentially a wrapper component inside the Angular SPA sample, we have extracted it into a new library in its own right, [just as we did for React](https://github.com/auth0/auth0-react).

So all of this wrapper code has been rewritten and packaged as a new library. We've also updated the [quickstart](https://auth0.com/docs/quickstart/spa/angular-next) and [the sample](https://github.com/auth0-samples/auth0-angular-samples/tree/update/new-sdk/Sample-01) to use this new SDK.

As this thread has continued for a while, with many reports of problems and struggles, I would be very keen to hear of anyone who tries out the new SDK and whether it solves your problem or makes your experience with using Auth0 and Angular together easier. If you try it out, the best place to provide feedback is the [issue tracker on the new repository](https://github.com/auth0/auth0-angular/issues).

I'll close this for now as we'll not be iterating on the sample code further, but I'm excited to hear feedback on the new bits!

**Closed by stevehobbsdev** 2020-08-17 15:00 UTC
