### ISSUE TITLE
Why refreshing the page automatically login?

### ISSUE THREAD

**Issue by guilhermecgs** [auth0-samples/auth0-angular-samples#127] opened 2018-11-12 16:12 UTC
Steps:

1. At least in example "06-Single-Sign-On", I login successfully on app01 and app02
2. I can see that localStorage localhost:3000 and localhost:3001 have the token ids stored...
3. I hit logout on both applications. I am redirected to main page -> "You are not logged in! Please Log In to continue."
4. Additionally, I clear the storage (devtools -> application -> clear storage) for both apps
5. I hit F5, and I successfully login on both apps again without asking my user/pass. Shouldn't it ask my password again?

**Comment by jimmyjames** [comment] 2019-06-24 21:19
Hi @guilhermecgs, since this issue was reported we've made a few changes to the sample in this area:
- It no longer stores tokens in `localStorage`
- It handles logout properly by calling the logout endpoint of the authorization server (Auth0).

I'm going to close this issue, but if you have continued issues don't hesitate to reopen or create a new issue, just be sure to include information to help us reproduce and debug. Thanks for the feedback!

**Closed by jimmyjames** 2019-06-24 21:19 UTC
